services:
  db:
    image: mysql:8.0
    container_name: pi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: supnum_alumni
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - pi_db_data:/var/lib/mysql
      - ./backend/setup/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - pi-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: pi-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=supnum_alumni
      - JWT_SECRET=supnum_connect_secret_key_2024_change_this
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pi-network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: pi-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pi-network

networks:
  pi-network:
    driver: bridge

volumes:
  pi_db_data:
